version: '3.9'

services:
  backend:
    container_name: server
    build:
      context: .
      dockerfile: docker/server/Dockerfile
    volumes:
      - static:/app/server/static
    restart: always
    ports:
      - 8000:8000
    env_file:
      - ./server/.env
    depends_on:
      - db

  db:
    image: postgres:15.3
    hostname: db
    container_name: db
    restart: always
    ports:
      - 5432:5432
    env_file:
      - ./server/.env
    volumes:
      - ./local_pg_data:/var/lib/postgresql/data

#  nginx:
#    container_name: nginx
#    build:
#      context: .
#      dockerfile: docker/nginx/Dockerfile
#    volumes:
#      - static:/app/backend/static
#      - ./docker/nginx/serts:/etc/nginx/ssl/:ro
#    restart: always
#    ports:
#      - 80:80
#      - 443:443


volumes:
  static: